language: go

env:
  - GO111MODULE=on

#branches:
  #only:
    #- dev

git:
  depth: false # Sonar doesn't like shallow clones

notifications:
  email: false

stages:
  - "Static Analysis, Unit Tests and Coverage"
  - test
  #- name: deploy
  #  if: branch = release

addons:
  apt:
    packages:
      - "python3"
      - "python3-dev"
      - "python3-pip"
      - "python3-setuptools"

dist: trusty

jobs:
  include:
    - stage: "Static Analysis, Unit Tests and Coverage"
      go: 1.14.x
      name: "GolangCI Linting, and Snyk Analysis"
      os: linux
      install:
        - pip3 install --upgrade pip
        - pip3 install pre-commit
        - pre-commit install
        - make prepare-lint
        - npm install -g snyk
      script:
        - pre-commit autoupdate
        - pre-commit run --all-files
        - snyk test
      after_success:
        - snyk monitor
    - go: 1.14.x
      name: "Unit Tests and Coverage"
      addons:
        sonarcloud:
          organization: "bytemare-github"
          token:
            secure: ${SONAR_TOKEN}
      os: linux
      install:
        - make prepare-tests
      script:
        - make cover
      after_success:
        - sonar-scanner -X
        #- bash <(curl -s https://codecov.io/bash)
        #- goveralls -coverprofile=coverage.out -service=travis-ci
    #- stage: release
    #  name: "Release a new version"
    #  deploy:
    #    provider: script
    #    cleanup: true
    #    script:
    #      - nvm install lts/*
    #      - npx semantic-release
    #    on:
    #      all_branches: true

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
os:
  - linux
  - osx
  - windows
script:
  - make test
